version: '3'

networks:
  newstack:
    driver: bridge

services:
  repl:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - newstack
    ports:
      - "17020:17020"
      - "4006:4006"
    volumes:
      - $HOME:$HOME
      - $PWD:$PWD
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - /tmp:/tmp
      - .:/app/
      - ./.cpcache:/app/.cpcache
    user: ${CURRENT_UID}

  db:
    image: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usuario
      - MONGO_INITDB_ROOT_PASSWORD=senha
    networks:
      - newstack
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo:/docker-entrypoint-initdb.d/
    ports:
      - "27017-27019:27017-27019"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - newstack
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    networks:
      - newstack
    depends_on:
      - zookeeper
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    networks:
      - newstack
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL

  kafka3:
    image: confluentinc/cp-kafka:latest
    hostname: kafka3
    networks:
      - newstack
    depends_on:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: "no"
    networks: 
      - newstack
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:19091
